grid_default:
    path:      /grid/{entity}/
    defaults:  { _controller: GridBundle:Grid:grid }

grid_elastic:
    path:      /grid/elastic/{entity}/{query}
    defaults:  { _controller: GridBundle:Grid:gridElastic, query: "" }