grid_default:
    path:      /grid/{gridName}/
    defaults:  { _controller: GridBundle:Grid:grid }

grid_elastic:
    path:      /grid/elastic/{gridName}/{query}
    defaults:  { _controller: GridBundle:Grid:gridElastic, query: "" }