language: php
php:
  - '7.0'
  
before_script: 
  - phpenv config-add travis.ini
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; fi;
  - composer install

script: phpunit
